### ISSUE TITLE
Contacts temporarily not available after deleting contact

### ISSUE THREAD

**Issue by KaiDol** [inofix/liferay-modules#15]
It sometimes happens that the contact module is not available after a single contact is deleted via the action dropdown menu. (see screenshot)

![bildschirmfoto 2015-06-29 um 12 54 43](https://cloud.githubusercontent.com/assets/6461005/8406594/2a4ce2a2-1e5e-11e5-9443-95c9e1db8afe.png)

**Comment by chrberndt** [comment]
Does this bug still occur in 0.3.1? And if yes: do you have any hints on how to reproduce this issue?

**Comment by KaiDol** [comment]
I've tested it with 0.3.1. and could reproduce it anymore.

**Comment by chrberndt** [comment]
hm - in 0.4.0 the error still occurs. But strange enough it seems to occur only on the very first page. 

I assume, this issue is caused by an asynchronous update of the index where records are still found which are already removed from the database. This results in a NPE when the app tries to load the record from the db.

**Comment by chrberndt** [comment]
The issue hab been fixed and the fix is deployed with 0.5.0-SNAPSHOT. In fact, the error resulted from the asynchronously updated search index.
