### ISSUE TITLE
portrait preview in contact list

### ISSUE THREAD

**Issue by KaiDol** [inofix/liferay-modules#16]
As a user I'd like to see the contact's image preview in the contact list, whenever it is available for an individual contact. If a contact has no image attached, a default image should be seen. 
If possible this preview should be distinguish mal / female / group / organization.

**Comment by chrberndt** [comment]
This feature has been implemented and will be available with snapshot 0.4.0. Distinction between male and female users has not been accomplished, since font awesome (http://fortawesome.github.io/Font-Awesome/icons/) does not support the concept of gendered users. 

The current implementation looks either for a PHOTO or a LOGO property. If neither of them was found, we distinguish between KIND="individual", "org", and "group". 

The style and size of the portrait can be configured via the portlets preferences.
